services:
  backend:
    build: ./backend
    ports:
      - 3667:3000
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_KEY}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_KEY}
        VITE_API_URL: http://backend:3667
    ports:
      - 80:5173
    environment:
      VITE_SUPABASE_URL: ${SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${SUPABASE_KEY}
      VITE_API_URL: http://backend:3667
    depends_on:
      - backend
